# Generated by Django 6.0.6 on 2026-06-30 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPaspor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('masa_berlaku_tahun', models.PositiveIntegerField()),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='KantorImigrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('kota', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Pemohon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('kewarganegaraan', models.CharField(default='Indonesia', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanPaspor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pengajuan', models.CharField(max_length=20, unique=True)),
                ('tanggal_pengajuan', models.DateField()),
                ('tujuan_pengajuan', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Diproses', 'Diproses'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak'), ('Selesai', 'Selesai')], default='Pending', max_length=20)),
                ('jadwal_wawancara', models.DateField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_paspor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengajuan', to='passport.jenispaspor')),
                ('kantor_imigrasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pengajuan', to='passport.kantorimigrasi')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan', to='passport.pemohon')),
            ],
            options={
                'ordering': ['-tanggal_pengajuan'],
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pembayaran', models.CharField(max_length=20, unique=True)),
                ('metode', models.CharField(choices=[('Transfer Bank', 'Transfer Bank'), ('QRIS', 'QRIS'), ('Kartu Kredit', 'Kartu Kredit')], max_length=30)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_bayar', models.DateField()),
                ('status', models.CharField(choices=[('Belum Bayar', 'Belum Bayar'), ('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Lunas', 'Lunas')], default='Belum Bayar', max_length=30)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='passport.pengajuanpaspor')),
            ],
            options={
                'ordering': ['-tanggal_bayar'],
            },
        ),
        migrations.CreateModel(
            name='PerpanjanganPaspor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_perpanjangan', models.CharField(max_length=20, unique=True)),
                ('nomor_paspor_lama', models.CharField(max_length=20)),
                ('tanggal_kadaluarsa', models.DateField()),
                ('tanggal_pengajuan', models.DateField()),
                ('alasan', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Diproses', 'Diproses'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak'), ('Selesai', 'Selesai')], default='Pending', max_length=20)),
                ('jadwal_pengambilan', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kantor_imigrasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perpanjangan', to='passport.kantorimigrasi')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perpanjangan', to='passport.pemohon')),
            ],
            options={
                'ordering': ['-tanggal_pengajuan'],
            },
        ),
    ]
